# Generated by Django 5.2.1 on 2025-07-15 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0002_alter_alumno_clasificacion_alter_alumno_grado_and_more'),
        ('escuelas', '0006_remove_escuela_clave_federal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroRAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('escuela', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_rae', to='escuelas.escuela', verbose_name='Escuela')),
            ],
        ),
        migrations.CreateModel(
            name='RAEAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(max_length=18, verbose_name='CURP')),
                ('genero', models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre')], max_length=1, verbose_name='Género')),
                ('edad', models.PositiveSmallIntegerField(verbose_name='Edad')),
                ('grado', models.CharField(max_length=10, verbose_name='Grado-Grupo')),
                ('ceg', models.BooleanField(default=False, verbose_name='Ceguera (CEG)')),
                ('bv', models.BooleanField(default=False, verbose_name='Baja visión (BV)')),
                ('so', models.BooleanField(default=False, verbose_name='Sordera (SO)')),
                ('hp', models.BooleanField(default=False, verbose_name='Hipoacusia (HP)')),
                ('scg', models.BooleanField(default=False, verbose_name='Sordoceguera (SCG)')),
                ('dmo', models.BooleanField(default=False, verbose_name='Discapacidad motriz (DMO)')),
                ('di', models.BooleanField(default=False, verbose_name='Discapacidad intelectual (DI)')),
                ('dme', models.BooleanField(default=False, verbose_name='Psicosocial/mental (DME)')),
                ('dm', models.BooleanField(default=False, verbose_name='Discapacidad múltiple (DM)')),
                ('dsc', models.BooleanField(default=False, verbose_name='DS Conducta (DSC)')),
                ('dsco', models.BooleanField(default=False, verbose_name='DS Comunicación (DSCO)')),
                ('dsa', models.BooleanField(default=False, verbose_name='DS Aprendizaje (DSA)')),
                ('tda', models.BooleanField(default=False, verbose_name='TDA/TDAH')),
                ('tea', models.BooleanField(default=False, verbose_name='TEA')),
                ('asi', models.BooleanField(default=False, verbose_name='AS Intelectual (ASI)')),
                ('asc', models.BooleanField(default=False, verbose_name='AS Creativa (ASC)')),
                ('asa', models.BooleanField(default=False, verbose_name='AS Artística (ASA)')),
                ('asp', models.BooleanField(default=False, verbose_name='AS Psicomotriz (ASP)')),
                ('ass', models.BooleanField(default=False, verbose_name='AS Socioafectiva (ASS)')),
                ('ot', models.BooleanField(default=False, verbose_name='Otra condición')),
                ('psicologia', models.BooleanField(default=False, verbose_name='Psicología')),
                ('comunicacion', models.BooleanField(default=False, verbose_name='Comunicación')),
                ('psicomotricidad', models.BooleanField(default=False, verbose_name='Psicomotricidad')),
                ('trabajo_social', models.BooleanField(default=False, verbose_name='Trabajo social')),
                ('aprendizaje', models.BooleanField(default=False, verbose_name='Aprendizaje')),
                ('nuevo_ingreso', models.BooleanField(default=False, verbose_name='Nuevo ingreso')),
                ('subsecuente', models.BooleanField(default=False, verbose_name='Subsecuente')),
                ('diagnostico', models.BooleanField(default=False, verbose_name='Diagnóstico médico/psicológico')),
                ('educativo', models.BooleanField(default=False, verbose_name='Diagnóstico educativo')),
                ('deteccion', models.BooleanField(default=False, verbose_name='Informe detección inicial')),
                ('psicopedagogico', models.BooleanField(default=False, verbose_name='Evaluación psicopedagógica')),
                ('plan', models.BooleanField(default=False, verbose_name='Plan de intervención')),
                ('modelo', models.BooleanField(default=False, verbose_name='Modelo de enriquecimiento')),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='alumnos.alumno', verbose_name='Alumno atendido')),
                ('capturado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Docente de apoyo')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='rae.registrorae', verbose_name='Registro RAE')),
            ],
            options={
                'verbose_name': 'Detalle RAE',
                'verbose_name_plural': 'Detalle RAE',
                'ordering': ['grado', 'alumno__apellido_paterno'],
            },
        ),
    ]
