# Generated by Django 5.2.1 on 2025-07-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rae', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raealumno',
            name='psicosocial',
            field=models.BooleanField(default=False, verbose_name='Psicosocial'),
        ),
        migrations.AlterField(
            model_name='raealumno',
            name='dme',
            field=models.BooleanField(default=False, verbose_name='Psicosocial (DME)'),
        ),
    ]
