# Generated by Django 5.2.1 on 2025-07-25 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0006_remove_escuela_clave_federal'),
        ('rae', '0002_raealumno_psicosocial_alter_raealumno_dme'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ciclo Escolar',
                'verbose_name_plural': 'Ciclos Escolares',
            },
        ),
        migrations.AlterModelOptions(
            name='registrorae',
            options={'ordering': ['escuela__nombre', 'ciclo_escolar__nombre'], 'verbose_name': 'Registro RAE', 'verbose_name_plural': 'Registros RAE'},
        ),
        migrations.AddField(
            model_name='registrorae',
            name='docente_hombres',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Número de Docentes Hombres'),
        ),
        migrations.AddField(
            model_name='registrorae',
            name='docente_mujeres',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Número de Docentes Mujeres'),
        ),
        migrations.AlterField(
            model_name='raealumno',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='raealumno',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='raealumno',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Mujer'), ('H', 'Hombre')], max_length=1, null=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='raealumno',
            name='grado',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Grado-Grupo'),
        ),
        migrations.AlterField(
            model_name='raealumno',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_alumnos', to='rae.registrorae', verbose_name='Registro RAE'),
        ),
        migrations.AlterField(
            model_name='registrorae',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_rae', to='escuelas.escuela', verbose_name='Escuela'),
        ),
        migrations.AddField(
            model_name='registrorae',
            name='ciclo_escolar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_rae', to='rae.cicloescolar', verbose_name='Ciclo Escolar'),
        ),
        migrations.AlterUniqueTogether(
            name='registrorae',
            unique_together={('escuela', 'ciclo_escolar')},
        ),
    ]
