# Generated by Django 5.2.1 on 2025-07-26 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rae', '0004_populate_registro_rae_ciclo_escolar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrorae',
            name='ciclo_escolar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='registros_rae', to='rae.cicloescolar', verbose_name='Ciclo Escolar'),
            preserve_default=False,
        ),
    ]
