# Generated by Django 5.2.1 on 2025-09-01 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alter_alumno_apellido_materno'),
        ('rae', '0005_alter_registrorae_ciclo_escolar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raealumno',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alumnos.alumno', verbose_name='Alumno atendido'),
        ),
        migrations.AlterUniqueTogether(
            name='raealumno',
            unique_together={('registro', 'alumno')},
        ),
    ]
