# Generated by Django 5.2.1 on 2025-10-14 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciclos_escolares', '0001_initial'),
        ('rac', '0005_alter_registrorac_ciclo_escolar'),
        ('rae', '0006_alter_raealumno_alumno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrorae',
            name='ciclo_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_rae', to='ciclos_escolares.cicloescolar', verbose_name='Ciclo Escolar'),
        ),
        migrations.DeleteModel(
            name='CicloEscolar',
        ),
    ]
