# Generated by Django 6.0.4 on 2026-05-22 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0007_alumno_last_promotion_cycle'),
        ('rae', '0007_alter_registrorae_ciclo_escolar_delete_cicloescolar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='raealumno',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rae_detalles', to='alumnos.alumno', verbose_name='Alumno atendido'),
        ),
        migrations.AlterField(
            model_name='raealumno',
            name='capturado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rae_alumnos_capturados', to=settings.AUTH_USER_MODEL, verbose_name='Docente de apoyo'),
        ),
        migrations.AlterField(
            model_name='registrorae',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_rae_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
