# Generated by Django 6.0.4 on 2026-06-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rae', '0008_alter_raealumno_alumno_alter_raealumno_capturado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrorae',
            name='cerrado',
            field=models.BooleanField(default=False, help_text='Una vez cerrado, no se puede modificar la captura. Solo se puede reabrir desde administración.', verbose_name='Registro cerrado'),
        ),
    ]
