# Generated by Django 6.0.4 on 2026-07-06 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0010_alter_alumno_escuela'),
        ('escuelas', '0009_alter_escuela_nivel'),
        ('rae', '0009_registrorae_cerrado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrorae',
            name='version',
            field=models.IntegerField(default=0, verbose_name='Versión de concurrencia'),
        ),
        migrations.AlterField(
            model_name='registrorae',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_rae', to='escuelas.escuela', verbose_name='Escuela'),
        ),
        migrations.AddIndex(
            model_name='raealumno',
            index=models.Index(fields=['alumno'], name='rae_alumno_idx'),
        ),
    ]
