# Generated by Django 6.0.4 on 2026-05-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
