# Generated by Django 6.0.4 on 2026-06-11 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_alter_notificacion_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', 'leida'], name='notif_usuario_leida_idx'),
        ),
    ]
