# Generated by Django 5.2.1 on 2025-05-29 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuelas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Descripción breve del problema', max_length=100, verbose_name='Título de la incidencia')),
                ('descripcion', models.TextField(help_text='Explica con detalle la incidencia', verbose_name='Descripción detallada')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reporte')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RESUELTA', 'Resuelta')], default='PENDIENTE', max_length=10, verbose_name='Estado')),
                ('respuesta_admin', models.TextField(blank=True, help_text='Comentarios de la dirección sobre la solución', null=True, verbose_name='Respuesta de dirección')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='escuelas.escuela', verbose_name='Escuela')),
                ('profesor', models.ForeignKey(limit_choices_to={'role': 'Profesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL, verbose_name='Profesor que reporta')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-fecha_reporte'],
                'permissions': [('can_resolve_incidence', 'Puede resolver incidencias')],
            },
        ),
    ]
