# Generated by Django 5.2.1 on 2025-05-21 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuelas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Describe el incidente o situación reportada', verbose_name='Descripción de la incidencia')),
                ('respuesta_admin', models.TextField(blank=True, null=True, verbose_name='Observaciones de la directora')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reporte')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuelas.escuela', verbose_name='Escuela')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.profesor', verbose_name='Profesor')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
