# Generated by Django 5.2.1 on 2025-07-06 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0003_alter_incidencia_profesor'),
        ('incidencias', '0003_incidencia_fecha_resolucion'),
    ]

    operations = [
    ]
