# Generated by Django 5.2.1 on 2025-09-02 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0004_merge_20250706_1446'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='reportado_por',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidencias_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'role': 'MAESTRO_APOYO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL, verbose_name='Profesor involucrado'),
        ),
    ]
