# Generated by Django 6.0.4 on 2026-06-11 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0009_alter_escuela_nivel'),
        ('incidencias', '0005_incidencia_reportado_por_alter_incidencia_profesor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['escuela', 'estado'], name='incidencia_escuela_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['profesor'], name='incidencia_profesor_idx'),
        ),
    ]
