# Generated by Django 5.2.1 on 2025-05-29 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuelas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PERSONAL', 'Personal'), ('ENFERMEDAD', 'Enfermedad'), ('COMISION', 'Comisión oficial'), ('LLEGADA_TARDE', 'Llegada tarde'), ('SALIDA_TEMPRANA', 'Salida temprana')], default='PERSONAL', max_length=15, verbose_name='Tipo de permiso')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('fecha_inicio', models.DateField(help_text='Fecha en que inicia el permiso solicitado', verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(help_text='Fecha en que finaliza el permiso solicitado', verbose_name='Fecha de finalización')),
                ('motivo', models.TextField(help_text='Explicación detallada del motivo de la solicitud', max_length=500, verbose_name='Motivo del permiso')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10, verbose_name='Estado')),
                ('respuesta_admin', models.TextField(blank=True, editable=False, help_text='Comentarios del administrador (obligatorio si se rechaza)', max_length=500, null=True, verbose_name='Respuesta del administrador')),
                ('fecha_respuesta', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de respuesta')),
                ('administrador', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_gestionados', to=settings.AUTH_USER_MODEL, verbose_name='Administrador que gestionó')),
                ('escuela', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='permisos_solicitados', to='escuelas.escuela', verbose_name='Escuela')),
                ('profesor', models.ForeignKey(limit_choices_to={'role': 'Profesor'}, on_delete=django.db.models.deletion.CASCADE, related_name='permisos_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Profesor solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud de permiso',
                'verbose_name_plural': 'Solicitudes de permiso',
                'ordering': ['-fecha_solicitud'],
                'permissions': [('gestionar_permisos', 'Puede aprobar/rechazar solicitudes de permiso')],
            },
        ),
    ]
