# Generated by Django 5.2.1 on 2025-05-26 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuelas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_permiso', models.CharField(choices=[('Personal', 'Personal'), ('Enfermedad', 'Enfermedad'), ('Comisión', 'Comisión'), ('Llegada Tarde', 'Llegada Tarde'), ('Salida Temprano', 'Salida Temprano')], max_length=30, verbose_name='Tipo de permiso')),
                ('motivo', models.TextField(verbose_name='Motivo del permiso')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=10, verbose_name='Estado')),
                ('comentario_admin', models.TextField(blank=True, null=True, verbose_name='Comentario del administrador')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuelas.escuela', verbose_name='Escuela')),
            ],
        ),
    ]
