# Generated by Django 5.2.1 on 2025-05-25 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0001_initial'),
        ('permisos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='permiso',
            name='comentario_admin',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario admin'),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuelas.escuela'),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha fin'),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha inicio'),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='motivo',
            field=models.TextField(verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'role': 'Profesor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
