# Generated by Django 5.2.1 on 2025-05-27 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuelas', '0001_initial'),
        ('permisos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='administrador',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_gestionados', to=settings.AUTH_USER_MODEL, verbose_name='Administrador que gestionó'),
        ),
        migrations.AddField(
            model_name='permiso',
            name='escuela',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='permisos_solicitados', to='escuelas.escuela', verbose_name='Escuela'),
        ),
        migrations.AddField(
            model_name='permiso',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'role': 'Profesor'}, on_delete=django.db.models.deletion.CASCADE, related_name='permisos_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Profesor solicitante'),
        ),
    ]
