# Generated by Django 5.2.1 on 2025-06-24 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0002_alter_permiso_profesor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'role': 'Profesor'}, on_delete=django.db.models.deletion.CASCADE, related_name='permisos_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Profesor solicitante'),
        ),
    ]
