# Generated by Django 5.2.1 on 2025-07-02 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0006_remove_escuela_clave_federal'),
        ('permisos', '0004_alter_permiso_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='escuela',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='permisos_escuela', to='escuelas.escuela', verbose_name='Escuela'),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='motivo',
            field=models.TextField(help_text='Explique claramente el motivo de su solicitud.', max_length=500, verbose_name='Motivo del permiso'),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='respuesta_admin',
            field=models.TextField(blank=True, editable=False, help_text='Explicación del rechazo (si aplica)', max_length=500, null=True, verbose_name='Respuesta del administrador'),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='tipo',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('ENFERMEDAD', 'Enfermedad'), ('COMISION', 'Comisión oficial'), ('LLEGADA_TARDE', 'Llegada tarde'), ('SALIDA_TEMPRANA', 'Salida temprana')], default='PERSONAL', max_length=20, verbose_name='Tipo de permiso'),
        ),
    ]
