# Generated by Django 5.2.1 on 2025-09-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0005_alter_permiso_escuela_alter_permiso_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='horas_solicitadas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Solo para permisos de llegada tarde o salida temprana.', max_digits=4, null=True, verbose_name='Horas solicitadas'),
        ),
    ]
