# Generated by Django 6.0.4 on 2026-06-11 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0009_alter_escuela_nivel'),
        ('permisos', '0006_permiso_horas_solicitadas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='permiso',
            index=models.Index(fields=['escuela', 'estado'], name='permiso_escuela_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='permiso',
            index=models.Index(fields=['profesor', 'estado'], name='permiso_profesor_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='permiso',
            index=models.Index(fields=['fecha_solicitud'], name='permiso_fecha_solicitud_idx'),
        ),
    ]
