# Generated by Django 5.2.1 on 2025-07-05 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Inicio del evento')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fin del evento')),
                ('tipo', models.CharField(choices=[('INSTITUCIONAL', 'Evento institucional'), ('PERSONAL', 'Evento personal')], default='PERSONAL', max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='calendario/archivos/')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Calendario',
                'verbose_name_plural': 'Eventos de Calendario',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
