# Generated by Django 6.0.4 on 2026-06-30 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0009_alumno_alumno_escuela_activo_idx_and_more'),
        ('calendario', '0001_initial'),
        ('escuelas', '0009_alter_escuela_nivel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocalendario',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='alumnos.alumno', verbose_name='Alumno relacionado'),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a'),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Código hex del color (ej. #EF4444)', max_length=7, verbose_name='Color del evento'),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='escuelas.escuela', verbose_name='Escuela relacionada'),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='event_type',
            field=models.CharField(choices=[('EVALUACION', 'Evaluación Psicopedagógica'), ('REUNION', 'Reunión con Padres'), ('VISITA', 'Visita a Escuela'), ('TAREA', 'Tarea Administrativa'), ('OTRO', 'Otro')], default='TAREA', max_length=20, verbose_name='Tipo de actividad'),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='priority',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
    ]
