# Generated by Django 6.0.4 on 2026-06-30 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_eventocalendario_alumno_eventocalendario_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocalendario',
            name='archivo',
        ),
    ]
