# Generated by Django 6.0.4 on 2026-06-30 17:28

from django.db import migrations


def migrar_eventos_existentes(apps, schema_editor):
    """Asigna valores coherentes a eventos creados antes de añadir los nuevos campos."""
    EventoCalendario = apps.get_model("calendario", "EventoCalendario")

    batch_size = 500
    ids = list(EventoCalendario.objects.values_list("pk", flat=True))

    for i in range(0, len(ids), batch_size):
        batch = EventoCalendario.objects.filter(pk__in=ids[i : i + batch_size])
        for evento in batch:
            if evento.tipo == "INSTITUCIONAL":
                evento.event_type = "REUNION"
                evento.priority = "ALTA"
                evento.color = "#EF4444"
            else:
                evento.event_type = "TAREA"
                evento.priority = "MEDIA"
                evento.color = "#3B82F6"
            evento.status = "PENDIENTE"
        EventoCalendario.objects.bulk_update(
            batch, ["event_type", "status", "priority", "color"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("calendario", "0003_remove_eventocalendario_archivo"),
    ]

    operations = [
        migrations.RunPython(migrar_eventos_existentes, migrations.RunPython.noop),
    ]
