# Generated by Django 5.2.1 on 2025-05-27 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuelas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('presente', models.BooleanField(verbose_name='Presente')),
                ('hora_entrada', models.TimeField(blank=True, null=True, verbose_name='Hora de entrada')),
                ('hora_salida', models.TimeField(blank=True, null=True, verbose_name='Hora de salida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuelas.escuela', verbose_name='Escuela')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
