# Generated by Django 5.2.1 on 2025-05-21 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuelas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre(s)')),
                ('apellido_paterno', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(max_length=50, verbose_name='Apellido materno')),
                ('domicilio', models.TextField(verbose_name='Domicilio particular')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono particular')),
                ('celular', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('rfc', models.CharField(max_length=13, verbose_name='R.F.C.')),
                ('curp', models.CharField(max_length=18, unique=True, verbose_name='C.U.R.P.')),
                ('clave_presupuestal', models.CharField(max_length=30, verbose_name='Clave presupuestal')),
                ('numero_empleado', models.CharField(max_length=20, verbose_name='Número de empleado')),
                ('numero_pensiones', models.CharField(max_length=20, verbose_name='Número de pensiones')),
                ('nivel', models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria')], max_length=20, verbose_name='Nivel educativo')),
                ('grado', models.CharField(help_text='Ejemplo: 1°, 2° a 3°, Todos', max_length=30, verbose_name='Grado(s) que atiende')),
                ('puesto', models.CharField(choices=[('Maestra de Apoyo', 'Maestra de Apoyo'), ('Psicólogo', 'Psicólogo'), ('Psicomotricista', 'Psicomotricista'), ('Trabajador Social', 'Trabajador Social')], max_length=30, verbose_name='Función')),
                ('situacion', models.CharField(choices=[('Base', 'Base'), ('Interino', 'Interino')], max_length=10, verbose_name='Situación')),
                ('escolaridad', models.CharField(max_length=100, verbose_name='Escolaridad')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('activo', models.BooleanField(default=True)),
                ('escuelas', models.ManyToManyField(to='escuelas.escuela', verbose_name='Escuelas asignadas')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
