# Generated by Django 5.2.1 on 2025-05-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('escuelas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_numero_empleado',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_curp',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_rfc',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_empleado__gt', '')), fields=('numero_empleado',), name='unique_numero_empleado'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('curp__gt', '')), fields=('curp',), name='unique_curp'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('rfc__gt', '')), fields=('rfc',), name='unique_rfc'),
        ),
    ]
