# Generated by Django 5.2.1 on 2025-06-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nivel',
            field=models.CharField(blank=True, choices=[('PRIM', 'Primaria'), ('SEC', 'Secundaria'), ('FIS', 'Educación Física')], help_text='Nivel educativo donde labora', max_length=4, verbose_name='Nivel educativo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='puesto',
            field=models.CharField(blank=True, choices=[('DIRECTOR', 'Director(a) de Escuela'), ('MAESTRO_APOYO', 'Maestro(a) de Apoyo'), ('TRAB_SOCIAL', 'Trabajador(a) Social'), ('PSICOLOGO', 'Psicólogo(a)'), ('PSICOMOTRICIDAD', 'Maestro(a) de Psicomotricidad'), ('COMUNICACION', 'Maestro(a) de Comunicación'), ('TRAB_MANUAL', 'Trabajador(a) Manual'), ('SECRETARIO', 'Secretario(a)'), ('ADMIN', 'Administrador(a)')], help_text='Puesto que desempeña en la institución', max_length=20, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DIRECTOR', 'Director(a) de Escuela'), ('MAESTRO_APOYO', 'Maestro(a) de Apoyo'), ('TRAB_SOCIAL', 'Trabajador(a) Social'), ('PSICOLOGO', 'Psicólogo(a)'), ('PSICOMOTRICIDAD', 'Maestro(a) de Psicomotricidad'), ('COMUNICACION', 'Maestro(a) de Comunicación'), ('TRAB_MANUAL', 'Trabajador(a) Manual'), ('SECRETARIO', 'Secretario(a)'), ('ADMIN', 'Administrador(a)')], db_index=True, default='MAESTRO_APOYO', max_length=30, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='situacion',
            field=models.CharField(blank=True, choices=[('BASE', 'Base'), ('HORAS', 'Por Horas'), ('INTER', 'Interino')], help_text='Situación contractual del empleado', max_length=5, verbose_name='Situación laboral'),
        ),
    ]

# Generated by Django 5.2.1 on 2025-06-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nivel',
            field=models.CharField(blank=True, choices=[('PRIM', 'Primaria'), ('SEC', 'Secundaria'), ('ESP', 'Educación Especial'), ('FIS', 'Educación Física')], help_text='Nivel educativo donde labora', max_length=4, verbose_name='Nivel educativo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='puesto',
            field=models.CharField(blank=True, choices=[('APOYO', 'Maestro(a) de Apoyo'), ('PSIC', 'Psicólogo(a)'), ('PSICO', 'Maestro(a) de Psicomotricidad'), ('TRAB', 'Trabajador(a) Social'), ('DIR', 'Director(a)'), ('ADMIN', 'Personal Administrativo'), ('EDFIS', 'Maestro(a) Educación Física'), ('MAN', 'Trabajador(a) Manual')], help_text='Puesto que desempeña en la institución', max_length=10, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('APOYO', 'Maestro(a) de Apoyo'), ('PSIC', 'Psicólogo(a)'), ('PSICO', 'Maestro(a) de Psicomotricidad'), ('TRAB', 'Trabajador(a) Social'), ('DIR', 'Director(a)'), ('ADMIN', 'Personal Administrativo'), ('EDFIS', 'Maestro(a) Educación Física'), ('MAN', 'Trabajador(a) Manual')], db_index=True, default='APOYO', max_length=30, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='situacion',
            field=models.CharField(blank=True, choices=[('BASE', 'Base'), ('HORAS', 'Por Horas'), ('INTER', 'Interino')], help_text='Situación contractual del empleado', max_length=5, verbose_name='Situación laboral'),
        ),
    ]
