# Generated by Django 5.2.1 on 2025-06-09 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_user_nivel_alter_user_puesto_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='celular',
            field=models.CharField(blank=True, help_text='Número de celular personal', max_length=15, validators=[django.core.validators.RegexValidator(message="El número debe tener entre 10 y 15 dígitos, puede comenzar con '+'.", regex='^\\+?\\d{10,15}$')], verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='user',
            name='curp',
            field=models.CharField(blank=True, help_text='Clave Única de Registro de Población', max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de CURP inválido. Asegúrate de que tenga 18 caracteres y siga el formato oficial.', regex='^[A-Z][AEIOU][A-Z]{2}\\d{6}[HM][A-Z]{5}[0-9A-Z]{2}$')], verbose_name='C.U.R.P.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nivel',
            field=models.CharField(blank=True, choices=[('PRIM', 'Primaria'), ('SEC', 'Secundaria'), ('FIS', 'Educación Física')], help_text='Nivel educativo donde labora', max_length=4, verbose_name='Nivel educativo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='puesto',
            field=models.CharField(blank=True, choices=[('DIRECTOR', 'Director(a) de Escuela'), ('MAESTRO_APOYO', 'Maestro(a) de Apoyo'), ('TRAB_SOCIAL', 'Trabajador(a) Social'), ('PSICOLOGO', 'Psicólogo(a)'), ('PSICOMOTRICIDAD', 'Maestro(a) de Psicomotricidad'), ('COMUNICACION', 'Maestro(a) de Comunicación'), ('TRAB_MANUAL', 'Trabajador(a) Manual'), ('SECRETARIO', 'Secretario(a)'), ('ADMIN', 'Administrador(a)')], help_text='Puesto que desempeña en la institución', max_length=20, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rfc',
            field=models.CharField(blank=True, help_text='Registro Federal de Contribuyentes', max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de RFC inválido. Debe seguir el formato oficial (12 o 13 caracteres).', regex='^[A-ZÑ&]{3,4}\\d{6}[A-Z0-9]{3}$')], verbose_name='R.F.C.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DIRECTOR', 'Director(a) de Escuela'), ('MAESTRO_APOYO', 'Maestro(a) de Apoyo'), ('TRAB_SOCIAL', 'Trabajador(a) Social'), ('PSICOLOGO', 'Psicólogo(a)'), ('PSICOMOTRICIDAD', 'Maestro(a) de Psicomotricidad'), ('COMUNICACION', 'Maestro(a) de Comunicación'), ('TRAB_MANUAL', 'Trabajador(a) Manual'), ('SECRETARIO', 'Secretario(a)'), ('ADMIN', 'Administrador(a)')], db_index=True, default='MAESTRO_APOYO', max_length=30, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono fijo de contacto', max_length=15, validators=[django.core.validators.RegexValidator(message="El número debe tener entre 10 y 15 dígitos, puede comenzar con '+'.", regex='^\\+?\\d{10,15}$')], verbose_name='Teléfono particular'),
        ),
    ]
