# Generated by Django 5.2.1 on 2025-05-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_user_unique_numero_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apellido_paterno',
            field=models.CharField(blank=True, help_text='Apellido paterno del usuario', max_length=50, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre(s) del usuario', max_length=50, verbose_name='Nombre(s)'),
        ),
    ]
