# Generated by Django 5.2.1 on 2025-06-09 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_user_celular_alter_user_curp_alter_user_nivel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Activo?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=50, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='user',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=50, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='user',
            name='celular',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="El número debe tener entre 10 y 15 dígitos, puede comenzar con '+'.", regex='^\\+?\\d{10,15}$')], verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='user',
            name='clave_presupuestal',
            field=models.CharField(blank=True, max_length=30, verbose_name='Clave presupuestal'),
        ),
        migrations.AlterField(
            model_name='user',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico alterno'),
        ),
        migrations.AlterField(
            model_name='user',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de CURP inválido. Asegúrate de que tenga 18 caracteres y siga el formato oficial.', regex='^[A-Z][AEIOU][A-Z]{2}\\d{6}[HM][A-Z]{5}[0-9A-Z]{2}$')], verbose_name='C.U.R.P.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='domicilio',
            field=models.TextField(blank=True, verbose_name='Domicilio particular'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Correo institucional del usuario', max_length=254, unique=True, verbose_name='Correo institucional'),
        ),
        migrations.AlterField(
            model_name='user',
            name='escolaridad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Escolaridad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grado',
            field=models.CharField(blank=True, max_length=30, verbose_name='Grado(s) que atiende'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nivel',
            field=models.CharField(blank=True, choices=[('PRIM', 'Primaria'), ('SEC', 'Secundaria'), ('FIS', 'Educación Física')], max_length=4, verbose_name='Nivel educativo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='numero_empleado',
            field=models.CharField(blank=True, help_text='Número único de empleado en el sistema', max_length=20, null=True, unique=True, verbose_name='Número de empleado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='numero_pensiones',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número de pensiones'),
        ),
        migrations.AlterField(
            model_name='user',
            name='puesto',
            field=models.CharField(blank=True, choices=[('DIRECTOR', 'Director(a) de Escuela'), ('MAESTRO_APOYO', 'Maestro(a) de Apoyo'), ('TRAB_SOCIAL', 'Trabajador(a) Social'), ('PSICOLOGO', 'Psicólogo(a)'), ('PSICOMOTRICIDAD', 'Maestro(a) de Psicomotricidad'), ('COMUNICACION', 'Maestro(a) de Comunicación'), ('TRAB_MANUAL', 'Trabajador(a) Manual'), ('SECRETARIO', 'Secretario(a)'), ('ADMIN', 'Administrador(a)')], max_length=20, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de RFC inválido. Debe seguir el formato oficial (12 o 13 caracteres).', regex='^[A-ZÑ&]{3,4}\\d{6}[A-Z0-9]{3}$')], verbose_name='R.F.C.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='situacion',
            field=models.CharField(blank=True, choices=[('BASE', 'Base'), ('HORAS', 'Por Horas'), ('INTER', 'Interino')], max_length=5, verbose_name='Situación laboral'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="El número debe tener entre 10 y 15 dígitos, puede comenzar con '+'.", regex='^\\+?\\d{10,15}$')], verbose_name='Teléfono particular'),
        ),
    ]
