# Generated by Django 5.2.1 on 2025-06-10 01:00

import usuarios.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_user_username_alter_user_activo_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', usuarios.managers.CustomUserManager()),
            ],
        ),
    ]
