# Generated by Django 5.2.1 on 2025-06-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nivel',
            field=models.CharField(blank=True, choices=[('PRIM', 'Primaria'), ('SEC', 'Secundaria'), ('FIS', 'Educación Física')], max_length=4, verbose_name='Escolaridad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DIRECTOR', 'Director(a) de Escuela'), ('MAESTRO_APOYO', 'Maestro(a) de Apoyo'), ('TRAB_SOCIAL', 'Trabajador(a) Social'), ('PSICOLOGO', 'Psicólogo(a)'), ('PSICOMOTRICIDAD', 'Maestro(a) de Psicomotricidad'), ('COMUNICACION', 'Maestro(a) de Comunicación'), ('TRAB_MANUAL', 'Trabajador(a) Manual'), ('SECRETARIO', 'Secretario(a)'), ('ADMIN', 'Administrador(a)')], db_index=True, default='MAESTRO_APOYO', max_length=30, verbose_name='Función'),
        ),
    ]
