# Generated by Django 5.2.1 on 2025-09-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_user_nivel_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nivel',
            field=models.CharField(blank=True, choices=[('PRE', 'Preescolar'), ('PRIM', 'Primaria'), ('SEC', 'Secundaria'), ('FIS', 'Educación Física')], max_length=4, verbose_name='Escolaridad'),
        ),
    ]
