# Generated by Django 5.2.1 on 2026-01-13 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_user_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='puesto',
        ),
    ]
