# Generated by Django 6.0.4 on 2026-05-22 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0007_alumno_last_promotion_cycle'),
        ('escuelas', '0009_alter_escuela_nivel'),
        ('usuarios', '0008_remove_user_puesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_nombre', models.CharField(default='USAER 7607', max_length=200, verbose_name='Nombre del Centro (USAER)')),
                ('centro_cct', models.CharField(default='08FUA0093E', max_length=20, verbose_name='CCT del Centro')),
                ('director_responsable', models.CharField(default='Nubia Idaly Solis Mendias', max_length=200, verbose_name='Nombre del Director Responsable')),
                ('sup_especial_cct', models.CharField(default='08FUA0041G', max_length=20, verbose_name='CCT Supervisión Especial')),
                ('sup_especial_zona', models.CharField(default='22', max_length=10, verbose_name='Zona Supervisión Especial')),
                ('ubicacion_centro', models.CharField(default='Juan Aldama, Chihuahua', max_length=200, verbose_name='Ubicación del Centro (Ciudad)')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('start_time', models.DateTimeField(verbose_name='Inicio')),
                ('end_time', models.DateTimeField(verbose_name='Fin')),
                ('event_type', models.CharField(choices=[('EVALUACION', 'Evaluación Psicopedagógica'), ('REUNION', 'Reunión con Padres'), ('VISITA', 'Visita a Escuela'), ('TAREA', 'Tarea Administrativa'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Tipo de evento')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=20, verbose_name='Prioridad')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Color del evento')),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumnos.alumno', verbose_name='Alumno relacionado')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('escuela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escuelas.escuela', verbose_name='Escuela relacionada')),
            ],
            options={
                'verbose_name': 'Evento/Tarea de Calendario',
                'verbose_name_plural': 'Eventos/Tareas de Calendario',
                'ordering': ['start_time'],
            },
        ),
    ]
