# Generated by Django 6.0.4 on 2026-06-11 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='anuncio',
            index=models.Index(fields=['fecha_publicacion', 'fecha_expiracion'], name='anuncio_vigencia_idx'),
        ),
        migrations.AddIndex(
            model_name='anuncio',
            index=models.Index(fields=['autor', 'fecha_publicacion'], name='anuncio_autor_fecha_idx'),
        ),
    ]
