# Generated by Django 5.2.1 on 2025-06-19 01:38

import django.db.models.deletion
import documentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0004_merge_20250901_1705'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informe_deteccion', models.FileField(upload_to=documentos.models.ruta_informe_deteccion, verbose_name='Informe de Detección Inicial')),
                ('informe_psicopedagogico', models.FileField(upload_to=documentos.models.ruta_informe_psicopedagogico, verbose_name='Informe Psicopedagógico')),
                ('plan_intervencion', models.FileField(upload_to=documentos.models.ruta_plan_intervencion, verbose_name='Plan de Intervención')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno', verbose_name='Alumno')),
                ('profesor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OtroArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=documentos.models.ruta_otros, verbose_name='Archivo adicional')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otros_archivos', to='documentos.expediente')),
            ],
        ),
    ]
