# Generated by Django 5.2.1 on 2025-05-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.CharField(max_length=100)),
                ('escuela', models.CharField(max_length=100)),
                ('grado', models.CharField(max_length=10)),
                ('grupo', models.CharField(max_length=10)),
                ('informe_deteccion', models.FileField(upload_to='expedientes/', verbose_name='Informe de Detección Inicial')),
                ('informe_psicopedagogico', models.FileField(upload_to='expedientes/', verbose_name='Informe Psicopedagógico')),
                ('plan_intervencion', models.FileField(upload_to='expedientes/', verbose_name='Plan de Intervención')),
                ('otros', models.FileField(blank=True, null=True, upload_to='expedientes/', verbose_name='Otros archivos')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
