# Generated by Django 5.2.1 on 2025-06-17 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informe_deteccion', models.FileField(upload_to='expedientes/', verbose_name='Informe de Detección Inicial')),
                ('informe_psicopedagogico', models.FileField(upload_to='expedientes/', verbose_name='Informe Psicopedagógico')),
                ('plan_intervencion', models.FileField(upload_to='expedientes/', verbose_name='Plan de Intervención')),
                ('otros', models.FileField(blank=True, null=True, upload_to='expedientes/', verbose_name='Otros archivos')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno', verbose_name='Alumno')),
                ('profesor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Profesor que sube')),
            ],
        ),
    ]
