# Generated by Django 5.2.1 on 2026-01-13 20:21

import django.db.models.deletion
import documentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='informe_deteccion',
            field=models.FileField(blank=True, null=True, upload_to=documentos.models.ruta_informe_deteccion, verbose_name='Informe de Detección Inicial'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='informe_psicopedagogico',
            field=models.FileField(blank=True, null=True, upload_to=documentos.models.ruta_informe_psicopedagogico, verbose_name='Informe Psicopedagógico'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='plan_intervencion',
            field=models.FileField(blank=True, null=True, upload_to=documentos.models.ruta_plan_intervencion, verbose_name='Plan de Intervención'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='profesor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
