# Generated by Django 5.2.1 on 2025-06-24 02:14

import documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='informe_deteccion',
            field=models.FileField(upload_to=documentos.models.ruta_informe_deteccion, verbose_name='Informe de Detección Inicial'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='informe_psicopedagogico',
            field=models.FileField(upload_to=documentos.models.ruta_informe_psicopedagogico, verbose_name='Informe Psicopedagógico'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='otros',
            field=models.FileField(blank=True, null=True, upload_to=documentos.models.ruta_otros, verbose_name='Otros archivos'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='plan_intervencion',
            field=models.FileField(upload_to=documentos.models.ruta_plan_intervencion, verbose_name='Plan de Intervención'),
        ),
    ]
