# Generated by Django 5.2.1 on 2025-06-24 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_alter_expediente_informe_deteccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='otros',
        ),
    ]
