# Generated by Django 5.2.1 on 2025-07-01 02:45

import oficios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='archivo',
            field=models.FileField(upload_to=oficios.models.ruta_archivo_oficio, verbose_name='Archivo'),
        ),
    ]

# Generated by Django 5.2.1 on 2025-07-01 22:54

import oficios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='archivo',
            field=models.FileField(upload_to=oficios.models.ruta_archivo_oficio, verbose_name='Archivo'),
        ),
    ]
