# Generated by Django 5.2.1 on 2025-07-01 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0002_alter_alumno_clasificacion_alter_alumno_grado_and_more'),
        ('escuelas', '0006_remove_escuela_clave_federal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cct', models.CharField(max_length=20, unique=True, verbose_name='CCT')),
                ('nombre', models.CharField(max_length=200, verbose_name='Centro Educación Especial')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('USAER', 'USAER'), ('CAM_BASICO', 'CAM Básico'), ('CAM_BASICO_FPT', 'CAM Básico con FpT'), ('CAM_LABORAL', 'CAM Laboral'), ('OTRO', 'Otro')], default='USAER', max_length=20, verbose_name='Tipo de servicio')),
                ('sup_especial_cct', models.CharField(default='08FUA0041G', max_length=20, verbose_name='CCT Supervisión')),
                ('sup_especial_zona', models.CharField(default='22', max_length=10, verbose_name='Zona Supervisión')),
                ('clasificacion', models.CharField(choices=[('DISCAPACIDAD', 'Con discapacidad'), ('DIFICULTADES_SEVERAS', 'Dificultades severas de aprendizaje'), ('TRASTORNOS', 'Trastornos'), ('APTITUDES_SOBRESALIENTES', 'Aptitudes sobresalientes'), ('NINGUNO', 'Ninguno'), ('OTRO', 'Otro')], max_length=30, verbose_name='Clasificación')),
                ('subclasificacion', models.CharField(choices=[('DI', 'Discapacidad intelectual'), ('DMO', 'Discapacidad motriz'), ('SO', 'Sordera'), ('HP', 'Hipoacusia'), ('CEG', 'Ceguera'), ('BV', 'Baja visión'), ('DM', 'Discapacidad múltiple'), ('SCG', 'Sordoceguera'), ('DME', 'Discapacidad mental o psicosocial'), ('NO_APLICA', 'No aplica'), ('DSC', 'Dificultades severas de conducta'), ('DSCO', 'Dificultades severas de comunicación'), ('DSA', 'Dificultades severas de aprendizaje'), ('NO_APLICA', 'No aplica'), ('TEA', 'Trastorno del espectro autista'), ('TDAH', 'Trastorno por Déficit de Atención e Hiperactividad'), ('NO_APLICA', 'No aplica'), ('ASI', 'Aptitudes sobresalientes intelectuales'), ('ASC', 'Aptitudes sobresalientes creativas'), ('ASS', 'Aptitudes sobresalientes socioafetivas'), ('ASA', 'Aptitudes sobresalientes artísticas'), ('ASP', 'Aptitudes sobresalientes psicomotrices'), ('NO_APLICA', 'No aplica')], help_text='Selecciona la subcategoría correspondiente', max_length=20, verbose_name='Subclasificación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno', verbose_name='Alumno')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rac.centrotrabajo', verbose_name='Centro Educación Especial')),
                ('escuela_basica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rac_basica', to='escuelas.escuela', verbose_name='Escuela básica')),
                ('escuela_regular', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rac_regular', to='escuelas.escuela', verbose_name='Escuela regular')),
                ('maestro_apoyo', models.ForeignKey(limit_choices_to={'role': 'MAESTRO_APOYO'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Maestro de apoyo')),
            ],
            options={
                'verbose_name': 'Registro RAC',
                'verbose_name_plural': 'Registros RAC',
                'ordering': ['-fecha_registro'],
                'unique_together': {('alumno', 'fecha_registro')},
            },
        ),
    ]
