# Generated by Django 5.2.1 on 2025-07-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rac', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrorac',
            name='centro',
        ),
        migrations.AddField(
            model_name='registrorac',
            name='centro_cct',
            field=models.CharField(default='08FUA0093E', max_length=20, verbose_name='CCT Centro Educación Especial'),
        ),
        migrations.AddField(
            model_name='registrorac',
            name='centro_nombre',
            field=models.CharField(default='USAER 7607', max_length=200, verbose_name='Nombre Centro Educación Especial'),
        ),
        migrations.DeleteModel(
            name='CentroTrabajo',
        ),
    ]
