# Generated by Django 5.2.1 on 2025-07-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rac', '0002_remove_registrorac_centro_registrorac_centro_cct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrorac',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CURP Alumno'),
        ),
        migrations.AddField(
            model_name='registrorac',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Edad Alumno'),
        ),
        migrations.AddField(
            model_name='registrorac',
            name='grado',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Grado Alumno'),
        ),
        migrations.AddField(
            model_name='registrorac',
            name='sexo',
            field=models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1, null=True, verbose_name='Sexo Alumno'),
        ),
        migrations.AddField(
            model_name='registrorac',
            name='zona_regular',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zona Escuela Regular'),
        ),
        migrations.AlterField(
            model_name='registrorac',
            name='subclasificacion',
            field=models.CharField(choices=[('DI', 'Discapacidad intelectual'), ('DMO', 'Discapacidad motriz'), ('SO', 'Sordera'), ('HP', 'Hipoacusia'), ('CEG', 'Ceguera'), ('BV', 'Baja visión'), ('DM', 'Discapacidad múltiple'), ('SCG', 'Sordoceguera'), ('DME', 'Discapacidad mental o psicosocial'), ('NO_APLICA', 'No aplica'), ('DSC', 'Dificultades severas de conducta'), ('DSCO', 'Dificultades severas de comunicación'), ('DSA', 'Dificultades severas de aprendizaje'), ('NO_APLICA', 'No aplica'), ('TEA', 'Trastorno del espectro autista'), ('TDAH', 'Trastorno por Déficit de Atención e Hiperactividad'), ('NO_APLICA', 'No aplica'), ('ASI', 'Aptitudes sobresalientes intelectuales'), ('ASC', 'Aptitudes sobresalientes creativas'), ('ASS', 'Aptitudes sobresalientes socioafetivas'), ('ASA', 'Aptitudes sobresalientes artísticas'), ('ASP', 'Aptitudes sobresalientes psicomotrices'), ('NO_APLICA', 'No aplica')], max_length=20, verbose_name='Subclasificación'),
        ),
    ]
