# Generated by Django 5.2.1 on 2025-09-01 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alter_alumno_apellido_materno'),
        ('rac', '0003_registrorac_curp_registrorac_edad_registrorac_grado_and_more'),
        ('rae', '0006_alter_raealumno_alumno_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registrorac',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='registrorac',
            name='ciclo_escolar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='racs', to='rae.cicloescolar', verbose_name='Ciclo Escolar'),
        ),
        migrations.AlterUniqueTogether(
            name='registrorac',
            unique_together={('alumno', 'ciclo_escolar')},
        ),
    ]
