# Generated by Django 5.2.1 on 2025-10-14 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciclos_escolares', '0001_initial'),
        ('rac', '0004_alter_registrorac_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrorac',
            name='ciclo_escolar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='racs', to='ciclos_escolares.cicloescolar', verbose_name='Ciclo Escolar'),
        ),
    ]
