# Generated by Django 6.0.4 on 2026-05-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rac', '0008_alter_registrorac_ciclo_escolar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrorac',
            name='centro_cct',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CCT Centro Educación Especial'),
        ),
        migrations.AlterField(
            model_name='registrorac',
            name='centro_nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Centro Educación Especial'),
        ),
        migrations.AlterField(
            model_name='registrorac',
            name='sup_especial_cct',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CCT Supervisión'),
        ),
        migrations.AlterField(
            model_name='registrorac',
            name='sup_especial_zona',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zona Supervisión'),
        ),
    ]
