# Generated by Django 5.2.1 on 2025-05-26 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuelas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(max_length=50, verbose_name='Apellido materno')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('curp', models.CharField(max_length=18, unique=True, verbose_name='C.U.R.P.')),
                ('sexo', models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre')], max_length=1, verbose_name='Sexo')),
                ('edad', models.PositiveSmallIntegerField(verbose_name='Edad')),
                ('grado', models.CharField(max_length=20, verbose_name='Grado')),
                ('clasificacion', models.CharField(choices=[('DISCAPACIDAD', 'Con discapacidad'), ('DIFICULTADES_SEVERAS', 'Dificultades severas'), ('TRASTORNOS', 'Trastornos'), ('APTITUDES_SOBRESALIENTES', 'Aptitudes sobresalientes'), ('NINGUNO', 'Ninguno'), ('OTRO', 'Otro')], max_length=30, verbose_name='Clasificación')),
                ('clasificacion_otro', models.CharField(blank=True, max_length=100, verbose_name='Otro (especificar)')),
                ('escuela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='escuelas.escuela')),
            ],
        ),
    ]
