# Generated by Django 5.2.1 on 2025-06-24 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='clasificacion',
            field=models.CharField(choices=[('DISCAPACIDAD', 'Con discapacidad'), ('DIFICULTADES_SEVERAS', 'Dificultades severas de aprendizaje'), ('TRASTORNOS', 'Trastornos'), ('APTITUDES_SOBRESALIENTES', 'Aptitudes sobresalientes'), ('NINGUNO', 'Ninguno'), ('OTRO', 'Otro')], max_length=30, verbose_name='Clasificación'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='grado',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=1, verbose_name='Grado'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Profesor responsable'),
        ),
    ]
