# Generated by Django 5.2.1 on 2025-07-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_alumno_clasificacion_alter_alumno_grado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='apellido_materno',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Apellido materno'),
        ),
    ]
