# Generated by Django 5.2.1 on 2025-09-01 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_alumno_clasificacion_alter_alumno_grado_and_more'),
        ('alumnos', '0003_alter_alumno_apellido_materno'),
    ]

    operations = [
    ]
