# Generated by Django 5.2.1 on 2025-09-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alumno_fecha_nacimiento_alter_alumno_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Está activo?'),
        ),
    ]
