# Generated by Django 5.2.1 on 2025-09-02 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_merge_20250901_1705'),
        ('alumnos', '0005_alumno_activo'),
    ]

    operations = [
    ]
