# Generated by Django 6.0.4 on 2026-05-20 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_merge_0004_merge_20250901_1705_0005_alumno_activo'),
        ('ciclos_escolares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='last_promotion_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos_promovidos', to='ciclos_escolares.cicloescolar', verbose_name='Último ciclo de promoción'),
        ),
    ]
