# Generated by Django 6.0.4 on 2026-06-10 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0007_alumno_last_promotion_cycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='edad',
        ),
    ]
