# Generated by Django 6.0.4 on 2026-06-11 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0008_remove_alumno_edad'),
        ('ciclos_escolares', '0001_initial'),
        ('escuelas', '0009_alter_escuela_nivel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['escuela', 'activo'], name='alumno_escuela_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['profesor', 'activo'], name='alumno_profesor_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['curp'], name='alumno_curp_idx'),
        ),
    ]
