# Generated by Django 6.0.4 on 2026-07-06 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0009_alumno_alumno_escuela_activo_idx_and_more'),
        ('escuelas', '0009_alter_escuela_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuelas.escuela', verbose_name='Escuela'),
        ),
    ]
