# Generated by Django 5.2.1 on 2025-10-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CicloEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. 2024-2025', max_length=100, unique=True, verbose_name='Nombre del ciclo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('activo', models.BooleanField(default=False, help_text='Marcar solo si este es el ciclo escolar actual. Solo un ciclo puede estar activo a la vez.', verbose_name='Ciclo activo')),
            ],
            options={
                'verbose_name': 'Ciclo Escolar',
                'verbose_name_plural': 'Ciclos Escolares',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
