# Generated by Django 5.2.1 on 2025-05-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('clave', models.CharField(max_length=20, unique=True, verbose_name='Clave de centro de trabajo')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('zona', models.CharField(max_length=50, verbose_name='Zona escolar')),
            ],
        ),
    ]
