# Generated by Django 5.2.1 on 2025-05-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_estatal', models.CharField(max_length=10, unique=True, verbose_name='Clave estatal')),
                ('clave_federal', models.CharField(max_length=20, unique=True, verbose_name='Clave federal')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('nivel', models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria')], max_length=20, verbose_name='Nivel educativo')),
                ('domicilio', models.CharField(max_length=200, verbose_name='Domicilio')),
                ('colonia', models.CharField(max_length=100, verbose_name='Colonia')),
                ('telefono_escuela', models.CharField(max_length=20, verbose_name='Teléfono escuela')),
                ('zona', models.CharField(max_length=10, verbose_name='Zona')),
                ('director', models.CharField(blank=True, max_length=100, verbose_name='Director/a')),
                ('cel_director', models.CharField(blank=True, max_length=20, verbose_name='Cel. Director/a')),
                ('correo_director', models.EmailField(blank=True, max_length=254, verbose_name='Correo Director/a')),
                ('inspector', models.CharField(blank=True, max_length=100, verbose_name='Inspector/a')),
                ('tel_inspector', models.CharField(blank=True, max_length=20, verbose_name='Tel. Inspector/a')),
                ('correo_inspector', models.EmailField(blank=True, max_length=254, verbose_name='Correo Inspector/a')),
                ('situacion', models.CharField(blank=True, max_length=50, verbose_name='Situación')),
            ],
        ),
    ]
