# Generated by Django 5.2.1 on 2025-05-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escuela',
            name='cel_directora',
        ),
        migrations.RemoveField(
            model_name='escuela',
            name='correo_directora',
        ),
        migrations.RemoveField(
            model_name='escuela',
            name='directora',
        ),
        migrations.AddField(
            model_name='escuela',
            name='cel_director',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cel. Director/a'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='correo_director',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo Director/a'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='director',
            field=models.CharField(blank=True, max_length=100, verbose_name='Director/a'),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='correo_inspector',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo Inspector/a'),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='inspector',
            field=models.CharField(blank=True, max_length=100, verbose_name='Inspector/a'),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='tel_inspector',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tel. Inspector/a'),
        ),
    ]
