# Generated by Django 5.2.1 on 2025-06-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escuela',
            name='cel_director',
        ),
        migrations.RemoveField(
            model_name='escuela',
            name='situacion',
        ),
        migrations.RemoveField(
            model_name='escuela',
            name='tel_inspector',
        ),
        migrations.RemoveField(
            model_name='escuela',
            name='telefono_escuela',
        ),
        migrations.AddField(
            model_name='escuela',
            name='celular_director',
            field=models.CharField(blank=True, max_length=20, verbose_name='Celular del director'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dirección física'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de la escuela'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='telefono_inspector',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono del inspector'),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='correo_director',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo del director'),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='correo_inspector',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo del inspector'),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='director',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del director/a'),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='inspector',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del inspector/a'),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre de la escuela'),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='zona',
            field=models.CharField(max_length=10, verbose_name='Zona escolar'),
        ),
    ]
