# Generated by Django 5.2.1 on 2025-06-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0002_remove_escuela_cel_director_remove_escuela_situacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escuela',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='escuela',
            name='nivel',
            field=models.CharField(choices=[('PRIMARIA', 'PRIMARIA'), ('SECUNDARIA', 'SECUNDARIA')], max_length=20, verbose_name='Nivel educativo'),
        ),
    ]
