# Generated by Django 5.2.1 on 2025-06-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0003_remove_escuela_direccion_alter_escuela_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuela',
            name='cct',
            field=models.CharField(default=0, max_length=20, unique=True, verbose_name='Clave de Centro de Trabajo (CCT)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='escuela',
            name='nivel',
            field=models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria')], max_length=20, verbose_name='Nivel educativo'),
        ),
    ]
