# Generated by Django 5.2.1 on 2025-06-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0004_escuela_cct_alter_escuela_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela',
            name='nivel',
            field=models.CharField(choices=[('Primaria', 'PRIMARIA'), ('Secundaria', 'SECUNDARIA')], max_length=20, verbose_name='Nivel educativo'),
        ),
    ]
