# Generated by Django 5.2.1 on 2025-06-29 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0005_alter_escuela_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escuela',
            name='clave_federal',
        ),
    ]
