# Generated by Django 5.2.1 on 2025-09-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0006_remove_escuela_clave_federal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela',
            name='nivel',
            field=models.CharField(choices=[('Preescolar', 'PREESCOLAR'), ('Primaria', 'PRIMARIA'), ('Secundaria', 'SECUNDARIA')], max_length=20, verbose_name='Nivel educativo'),
        ),
    ]
