# Generated by Django 6.0.4 on 2026-05-20 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0007_alter_escuela_nivel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escuelas_dirigidas', to=settings.AUTH_USER_MODEL, verbose_name='Director(a)'),
        ),
    ]
