# Generated by Django 6.0.4 on 2026-05-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0008_alter_escuela_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela',
            name='nivel',
            field=models.CharField(choices=[('PREESCOLAR', 'Preescolar'), ('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria')], max_length=20, verbose_name='Nivel educativo'),
        ),
    ]
