"""
Django settings for usaer_system project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.contrib.auth import get_user_model
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!8659yl2gf6**0m*l05cuq1%maailzw$nu*x7wmt&+pix39evh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'usuarios.User'

AUTHENTICATION_BACKENDS = [
    'usuarios.backends.EmailOrEmpleadoBackend',       
    'django.contrib.auth.backends.ModelBackend',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # mis apps
    'usuarios.apps.UsuariosConfig',
    'escuelas.apps.EscuelasConfig',
    'asistencias',
    'permisos',
    'incidencias',
    'documentos',
    'alumnos',
    
    
    #dependencias
    'crispy_forms',
    'crispy_bootstrap5',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'usaer_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.debug',
            ],
        },
    },
]

WSGI_APPLICATION = 'usaer_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    
    {
        'NAME': 'usaer_system.validators.CustomPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Chihuahua'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/usuarios/redireccion/'
LOGOUT_REDIRECT_URL = '/'

# settings.py

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


ROLE_PERMISSIONS = {
    'ADMIN': [
        'manage_users',
        'manage_escuelas',
        'export_rae_rac',
        'manage_documents_admin',
        'subir_expediente',
        'lista_expedientes',
        'editar_expediente',         
        'listar_global',           
        'view_incidencias',
        'manage_permisos',
        'manage_asistencias',
        'manage_alumnos',
    ],
    'DIRECTOR': [
        'view_incidencias',
        'view_calendario',
        'lista_expedientes',
    ],
    'SECRETARIO': [
        'manage_users',
        'manage_escuelas',
        'manage_documents_admin',
        'subir_expediente',
        'lista_expedientes',
        'editar_expediente',         
        'listar_global',             
        'export_rae_rac',
        'manage_permisos',
        'manage_asistencias',
    ],
    'MAESTRO_APOYO': [
        'capture_rae_rac',
        'manage_alumnos',
        'manage_expedientes',
        'view_permisos',
        'manage_asistencias',
        'subir_expediente',
        'lista_expedientes',
    ],
    'TRAB_SOCIAL': [
        'upload_to_expedientes',
        'manage_permisos',
        'manage_asistencias',
        'download_official_docs',
        'lista_expedientes',
        'editar_expediente',         
        'listar_global',             
    ],
    'PSICOLOGO': [
        'upload_to_expedientes',
        'manage_permisos',
        'manage_asistencias',
        'download_official_docs',
        'lista_expedientes',
        'editar_expediente',         
        'listar_global',             
    ],
    'PSICOMOTRICIDAD': [
        'upload_to_expedientes',
        'manage_permisos',
        'manage_asistencias',
        'download_official_docs',
        'lista_expedientes',
        'editar_expediente',         
        'listar_global',             
    ],
    'COMUNICACION': [
        'upload_to_expedientes',
        'manage_permisos',
        'manage_asistencias',
        'download_official_docs',
        'lista_expedientes',
        'editar_expediente',         
        'listar_global',             
    ],
    'TRAB_MANUAL': [
        'manage_permisos',
        'manage_asistencias',
        'lista_expedientes',
    ],
}



DASHBOARD_MODULES = [
    {
        'key': 'manage_users',
        'title': 'Gestión de Usuarios',
        'url': 'usuarios:list',
        'icon': 'fas fa-users text-primary',
    },
    {
        'key': 'manage_escuelas',
        'title': 'Gestión de Escuelas',
        'url': 'escuelas:listar_escuelas',
        'icon': 'fas fa-school text-success',
    },
    {
        'key': 'export_rae_rac',
        'title': 'Exportar RAC',
        'url': 'alumnos:exportar_rac',
        'icon': 'fas fa-file-export text-warning',
    },
    {
        'key': 'manage_documents_admin',
        'title': 'Control de Documentos',
        'url': 'documentos:subir_expediente',
        'icon': 'fas fa-folder-open text-info',
    },
    {
        'key': 'view_incidencias',
        'title': 'Revisar Incidencias',
        'url': 'incidencias:listar_incidencias',
        'icon': 'fas fa-exclamation-triangle text-danger',
    },
    {
        'key': 'manage_permisos',
        'title': 'Gestionar Permisos',
        'url': 'permisos:gestionar',
        'icon': 'fas fa-check-circle text-success',
    },
    {
        'key': 'view_permisos',
        'title': 'Mis Permisos',
        'url': 'permisos:mis_permisos',
        'icon': 'fas fa-user-clock text-info',
    },
    {
        'key': 'manage_asistencias',
        'title': 'Gestión de Asistencias',
        'url': 'asistencias:listar_asistencias',
        'icon': 'fas fa-calendar-check text-primary',
    },
    {
        'key': 'manage_alumnos',
        'title': 'Gestión de Alumnos',
        'url': 'alumnos:listar_alumnos',
        'icon': 'fas fa-user-graduate text-info',
    },
    {
        'key': 'subir_expediente',
        'title': 'Subir Expediente',
        'url': 'documentos:subir_expediente',
        'icon': 'fas fa-upload text-primary',
    },
    {
        'key': 'lista_expedientes',
        'title': 'Lista de Expedientes',
        'url': 'documentos:lista_expedientes',
        'icon': 'fas fa-list text-secondary',
    },
    ]