"""
Django settings for usaer_system project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.contrib.auth import get_user_model
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!8659yl2gf6**0m*l05cuq1%maailzw$nu*x7wmt&+pix39evh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'usuarios.User'

AUTHENTICATION_BACKENDS = [
    'usuarios.backends.EmailOrEmpleadoBackend',       
    'django.contrib.auth.backends.ModelBackend',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # mis apps
    'usuarios.apps.UsuariosConfig',
    'escuelas.apps.EscuelasConfig',
    'asistencias',
    'permisos',
    'incidencias',
    'documentos',
    'alumnos',
    #'oficios',
    
    
    #dependencias
    'crispy_forms',
    'crispy_bootstrap5',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'usaer_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.debug',
                'usuarios.context_processors.permisos_usuario',
            ],
        },
    },
]

WSGI_APPLICATION = 'usaer_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    
    {
        'NAME': 'usaer_system.validators.CustomPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Chihuahua'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/usuarios/redireccion/'
LOGOUT_REDIRECT_URL = '/'

# settings.py

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# settings.py (fragmento corregido)

# ----------------------------------------------------------------
# Funciones permitidas según rol para el dashboard
# ----------------------------------------------------------------
# settings.py (fragmento)

ROLE_PERMISSIONS = {
    'ADMIN': [
        # Usuarios CRUD
        'create_user', 'list_users', 'edit_user', 'delete_user',
        # Escuelas CRUD
        'create_escuela', 'list_escuelas', 'edit_escuela', 'delete_escuela',
        # Alumnos CRUD
        'create_alumno', 'list_alumnos', 'edit_alumno', 'delete_alumno',
        # RAE/RAC
        'export_rae_rac', 'capture_rae_rac',
        # Expedientes CRUD + descarga oficial
        'create_expediente', 'list_expedientes', 'edit_expediente', 'delete_expediente',
        'download_official_docs',
        # Incidencias CRUD
        'create_incidencia', 'list_incidencias', 'edit_incidencia', 'delete_incidencia',
        # Permisos
        'manage_permisos',
        # Asistencias
        'check_asistencia', 'list_asistencias',
    ],

    'DIRECTOR': [
        'list_incidencias',   # listar_incidenicas reemplaza view_incidencias
    ],

    'SECRETARIO': [
        # Usuarios CRUD
        'create_user', 'list_users', 'edit_user', 'delete_user',
        # Escuelas CRUD
        'create_escuela', 'list_escuelas', 'edit_escuela', 'delete_escuela',
        # RAE/RAC
        'export_rae_rac',
        # Expedientes CRUD + descarga oficial
        'create_expediente', 'list_expedientes', 'edit_expediente', 'delete_expediente',
        'download_official_docs',
        # Permisos
        'manage_permisos',
        # Asistencias
        'check_asistencia', 'list_asistencias',
    ],

    'MAESTRO_APOYO': [
        # Alumnos CRUD
        'create_alumno', 'list_alumnos', 'edit_alumno',
        # RAE/RAC
        'export_rae_rac', 'capture_rae_rac',
        # Expedientes CRUD + descarga oficial
        'create_expediente', 'list_expedientes', 'edit_expediente', 'delete_expediente',
        'download_official_docs',
        # Permisos
        'manage_permisos',
        # Asistencias
        'check_asistencia', 'list_asistencias',
    ],

    # Equipo itinerante: sólo listar/editar expediente y descarga oficial
    'TRAB_SOCIAL': [
        'list_expedientes', 'edit_expediente', 'download_official_docs',
        'manage_permisos',
        'check_asistencia', 'list_asistencias',
    ],
    'PSICOLOGO': [
        'list_expedientes', 'edit_expediente', 'download_official_docs',
        'manage_permisos',
        'check_asistencia', 'list_asistencias',
    ],
    'PSICOMOTRICIDAD': [
        'list_expedientes', 'edit_expediente', 'download_official_docs',
        'manage_permisos',
        'check_asistencia', 'list_asistencias',
    ],
    'COMUNICACION': [
        'list_expedientes', 'edit_expediente', 'download_official_docs',
        'manage_permisos',
        'check_asistencia', 'list_asistencias',
    ],

    'TRAB_MANUAL': [
        # Puede descargar y ver lista
        'download_official_docs', 'list_expedientes',
        # Permisos y asistencias
        'manage_permisos',
        'check_asistencia', 'list_asistencias',
    ],
}



# ----------------------------------------------------------------
# Metadatos de todos los módulos disponibles en el dashboard
# ----------------------------------------------------------------
# ----------------------------------------------------------------
# Metadatos de todos los módulos disponibles en el dashboard
# ----------------------------------------------------------------
DASHBOARD_MODULES = [
    # --- Usuarios CRUD ---
    {
        'key': 'create_user',
        'title': 'Crear Usuario',
        'url_name': 'usuarios:create',
        'icon': 'fas fa-user-plus text-primary',
    },
    {
        'key': 'list_users',
        'title': 'Listar Usuarios',
        'url_name': 'usuarios:list',
        'icon': 'fas fa-users text-primary',
    },
    {
        'key': 'edit_user',
        'title': 'Editar Usuario',
        'url_name': 'usuarios:update',
        'icon': 'fas fa-user-edit text-warning',
        'needs_pk': True,
    },
    {
        'key': 'delete_user',
        'title': 'Eliminar Usuario',
        'url_name': 'usuarios:delete',
        'icon': 'fas fa-user-slash text-danger',
        'needs_pk': True,
    },

    # --- Escuelas CRUD ---
    {
        'key': 'create_escuela',
        'title': 'Crear Escuela',
        'url_name': 'escuelas:crear_escuela',
        'icon': 'fas fa-school-plus text-success',
    },
    {
        'key': 'list_escuelas',
        'title': 'Listar Escuelas',
        'url_name': 'escuelas:listar_escuelas',
        'icon': 'fas fa-school text-success',
    },
    {
        'key': 'edit_escuela',
        'title': 'Editar Escuela',
        'url_name': 'escuelas:editar_escuela',
        'icon': 'fas fa-edit text-warning',
        'needs_pk': True,
    },
    {
        'key': 'delete_escuela',
        'title': 'Eliminar Escuela',
        'url_name': 'escuelas:eliminar_escuela',
        'icon': 'fas fa-trash text-danger',
        'needs_pk': True,
    },

    # --- Alumnos CRUD ---
    {
        'key': 'create_alumno',
        'title': 'Crear Alumno',
        'url_name': 'alumnos:crear_alumno',
        'icon': 'fas fa-user-graduate text-info',
    },
    {
        'key': 'list_alumnos',
        'title': 'Listar Alumnos',
        'url_name': 'alumnos:listar_alumnos',
        'icon': 'fas fa-users text-info',
    },
    {
        'key': 'edit_alumno',
        'title': 'Editar Alumno',
        'url_name': 'alumnos:editar_alumno',
        'icon': 'fas fa-edit text-warning',
        'needs_pk': True,
    },
    {
        'key': 'delete_alumno',
        'title': 'Eliminar Alumno',
        'url_name': 'alumnos:eliminar_alumno',
        'icon': 'fas fa-trash text-danger',
        'needs_pk': True,
    },

    # --- Expedientes CRUD (Documentos) ---
    {
        'key': 'create_expediente',
        'title': 'Crear Expediente',
        'url_name': 'documentos:subir_expediente',
        'icon': 'fas fa-file-upload text-primary',
    },
    {
        'key': 'list_expedientes',
        'title': 'Listar Expedientes',
        'url_name': 'documentos:lista_expedientes',
        'icon': 'fas fa-file-alt text-secondary',
    },
    {
        'key': 'edit_expediente',
        'title': 'Editar Expediente',
        'url_name': 'documentos:editar_expediente',
        'icon': 'fas fa-edit text-warning',
        'needs_pk': True,
    },
    {
        'key': 'delete_expediente',
        'title': 'Eliminar Expediente',
        'url_name': 'documentos:eliminar_expediente',
        'icon': 'fas fa-trash-alt text-danger',
        'needs_pk': True,
    },

    # --- Incidencias CRUD ---
    {
        'key': 'create_incidencia',
        'title': 'Crear Incidencia',
        'url_name': 'incidencias:crear_incidencia',
        'icon': 'fas fa-exclamation-circle text-warning',
    },
    {
        'key': 'list_incidencias',
        'title': 'Listar Incidencias',
        'url_name': 'incidencias:listar_incidencias',
        'icon': 'fas fa-list-alt text-danger',
    },
    {
        'key': 'edit_incidencia',
        'title': 'Editar Incidencia',
        'url_name': 'incidencias:editar_incidencia',
        'icon': 'fas fa-edit text-warning',
        'needs_pk': True,
    },
    {
        'key': 'delete_incidencia',
        'title': 'Eliminar Incidencia',
        'url_name': 'incidencias:eliminar_incidencia',
        'icon': 'fas fa-trash text-danger',
        'needs_pk': True,
    },

    # --- Permisos ---
    {
        'key': 'create_permiso',
        'title': 'Solicitar Permiso',
        'url_name': 'permisos:solicitar',
        'icon': 'fas fa-calendar-plus text-primary',
    },
    {
        'key': 'list_my_permisos',
        'title': 'Mis Permisos',
        'url_name': 'permisos:mis_permisos',
        'icon': 'fas fa-user-clock text-info',
    },
    {
        'key': 'manage_permisos',
        'title': 'Gestionar Permisos',
        'url_name': 'permisos:gestionar',
        'icon': 'fas fa-check-circle text-success',
    },

    # --- Asistencias ---
    {
        'key': 'check_asistencia',
        'title': 'Checar Asistencia',
        'url_name': 'asistencias:checar_asistencia',
        'icon': 'fas fa-sign-in-alt text-primary',
    },
    {
        'key': 'list_asistencias',
        'title': 'Listar Asistencias',
        'url_name': 'asistencias:listar_asistencias',
        'icon': 'fas fa-calendar-alt text-primary',
    },

    # --- Descarga de documentos oficiales ---
    {
        'key': 'download_official_docs',
        'title': 'Descargar Documentos Oficiales',
        'url_name': 'documentos:lista_expedientes',
        'icon': 'fas fa-download text-secondary',
    },
]
